Module4 task1
htmlacademy-adaptive/1466403-sedona-20 pull request #4
Opened 2020-09-06 02:12 UTC by tgazaryan

Привет.
Я очень прошу прощения за то, что я пропала так резко и не предупредив. К моему сожалению, так сложились обстоятельства, что я из учебы выпала на месяц.
Я понимаю, что вероятно уже естественно не успею до защиты закончить проект, но я буду очень благодарна, если получится посмотреть и дать комментарии. Даже если не успею защититься, то получится понять.
Спасибо большое.

2020-09-06 09:36 UTC, ILoyso requested changes
Привет! 
Ничего страшного, всякое случается. Вряд ли мы уже успеем доделать проект до конца, но как минимум поработать и пройти какой-нибудь материал можем.

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/page.less
> +  }
Если какое-то правило уже задано для меньшего разрешения, то не нужно дублировать его на более широком, если нет необходимости его изменять.
Здесь нужно убрать дублирование на десктопе display: grid, grid-template-rows: min-content 1fr min-content.
А margin: 0 auto можно изначально написать для телефона и соответственно на десктопе тоже убрать

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/page.less
>  }
Удаляем. Не нужно ставить флекс колонки там, где они не нужны. В данном случае у нас все элементы - блочные и они изначально идут друга за другом в потоке

2020-09-06 09:36 UTC, ILoyso commented on source/less/global/variables.less
> +@grey-3: #E6E6E6;
Если что, на этом интенсиве нет критерия, по которому нужно все цвета выносить в переменные. Если цвет используется один раз, то создавать для него переменную избыточно

2020-09-06 09:36 UTC, ILoyso commented on source/less/global/variables.less
> +@mobile-width: 767px;
https://up.htmlacademy.ru/adaptive/20/criteries#b11
В критерии указаны значения брейкпоинтов для Седоны
Планшет и мобилка у нас не могут отличаться в один пиксель, значение этих переменных - минимальная ширина для каждого брейкпоинта

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/features.less
> +}
- убираем флекс колонку там, где она не нужна
- убираем дублирование неизменяющихся css правил для планшета

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/features.less
> +    padding-bottom: 60px;
Если пишем паддинги не вместе, а отдельно для каждой стороны, то в рамках этого css правила лучше все так писать. Сначала padding, а потом padding-top и padding-bottom воспринимать тяжело

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/features.less
> +  }
Аналогично

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/features-numbered.less
> +  }
- background-repeat: no-repeat; пишем один раз для мобилки не повторяем больше на планшете и десктопе
- добавляем background-size: cover
- background-position: center; тоже пишем для мобилки и переопределяем только там, где нужно
- ширину можно вынести из модификатора и написать в медиаусловии именно для элемента. Тогда у модификаторов не нужно будет писать её дважды

Причем стили пишем не у модификатора, а у основного класса, потому что они актуальны для обоих модификаторов. Сейчас из-за этого много дублирования кода

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/features-numbered.less
> +    }
Неочевидная запить, не нужно так. А если порядок поменяется в разметке?
Добавляем класс-модификатор и для него делаем reverse

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/map.less
> +}
Дублирующиеся стили удаляем

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/page-footer.less
> +  flex-direction: column;
На мобилке флекс-колонка не нужна

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/photo.less
> +  justify-content: center;
Нет необходимости в колонке на мобилке

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/photo-card.less
> +  flex-direction: column;
Не нужна колонка

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/photo-card.less
> +.photo__container figcaption {
При организации стилей по БЭМ лучше не стилизовать по тегам, а задавать им классы и использовать их

2020-09-06 09:36 UTC, ILoyso commented on source/photo.html
> +        <div class="photo-card photo-card--secondary">
Модификаторы photo-card--secondary задавать нет необходимости. Для photo-card мы пишем поведение маленьких карточек, для модификатора photo-card--main описываем поведение большой.
На планшете и декстопе поведение большой карточки сейчас не описано, нужно сделать

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/top.less
>  }
Убираем дублирующиеся стили

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/review-form.less
> +  flex-direction: column;
Не нужна колонка

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/review-form.less
> +  margin: 0;
Аналогично, не нужна колонка, абзацы идут друг за другом по умолчанию, а легенду можно сделать блочной

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/review-form.less
> +  }
Удаляем дублирующиеся с мобилкой стили

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/review-form.less
> +  justify-content: space-between;
Аналогично, флекс ничего не делаем здесь на мобилке. Смотри пожалуйста внимательнее, зачем мы пишем каждое свойство, что изменяется на странице с его появлением и точно ли оно нам нужно здесь

2020-09-06 09:36 UTC, ILoyso commented on source/less/blocks/review-form.less
> +  &--contacts {
Точно ли есть смысл в уникальном модификаторе на каждый блок формы? У некоторых поведние совпадает друг с другом, а значит им можно иметь один общий модификатор.
Плюс должно быть какое-то общее состояние, например когда ширина 100%. Соответственно для него и не нужны будут модификаторы

2020-09-06 12:27 UTC, tgazaryan commented on source/less/blocks/review-form.less
> +  margin: 0;
В данном случае, декоративные рамки между блоками стоит делать псевдоэлементами или через border?
Просто если первое, то можно в принципе было бы убрать позиционирование этой легенды относительно блока.

2020-09-06 19:25 UTC, ILoyso commented on source/less/blocks/review-form.less
> +  margin: 0;
Если можно бордерами, то почему бы и нет. Это проще, чем псевдоэлементы, а значит если есть возможность, то лучше выбирать наиболее простые решения :)

2020-09-06 19:29 UTC, tgazaryan commented on source/less/blocks/review-form.less
> +  margin: 0;
Это проще без сомнения :) Я просто задумалась, правильна ли сама концепция абсолютного позиционирования легенды, чтобы она не торчала посередине рамки (как она обычно в fieldset по умолчанию). Или есть еще методы?

2020-09-06 19:42 UTC, ILoyso requested changes
source/less/blocks/допник - нужно удалить

2020-09-06 19:42 UTC, ILoyso commented on source/less/blocks/main-nav.less
>  }
Для планшета марджин убираем - он уже задан для мобилки и наследуется
Наши медиаусловия звучит как "минимальная ширина" и это значит, что для планшета и десктопа мы только задаем новые свойства и переопределяем старые, которые нам не подходят. А если свойство не меняется, то его и не нужно писать повторно

2020-09-06 19:42 UTC, ILoyso commented on source/less/blocks/features.less
> +  }
Кстати тут тоже лучше не через nth-child, а модификатором

2020-09-06 19:42 UTC, ILoyso commented on source/less/blocks/map.less
> +}
Мы до этого везде писали медиаусловия внутри блока (то есть внутри map в данном случае), давай придерживаться единообразного подхода

2020-09-06 19:42 UTC, ILoyso commented on source/less/blocks/photo-card.less
> +}
У нас сейчас получается, что файл называется photo-card и подразумевается, что здесь должны лежать стили только от этого блока. А начиная отсюда и ниже у нас стили для блока photo, значит их нужно перенести в соответствующий файл
Если ещё где-то такое встречается, то нужно поправить. На это есть базовый критерий, плюс в целом это противоречит подходу, когда один файл - один блок :)

2020-09-06 19:43 UTC, ILoyso commented on source/less/blocks/review-form.less
> +  margin: 0;
На самом деле, очень часто от легенды отказываются в пользу тегов заголовков, потому что легенда немного по разному выгляди в Фаерфоксе и Хроме и в определенных случаях это никак не исправить. Заодно автоматически исчезает проблема с легендой посередине рамки :)

2020-09-06 20:12 UTC, tgazaryan commented on source/less/blocks/review-form.less
> +  margin: 0;
А у нас подобное решение разрешается в проекте? 
Потому что тогда это было бы значительно удобнее и не нужно страдать с паддингами, чтобы компенсировать за выпавшую из потока легенду :)

2020-09-06 20:24 UTC, ILoyso commented on source/less/blocks/review-form.less
> +  margin: 0;
Да, разрешается )

2020-09-07 07:38 UTC, ILoyso approved these changes

2020-09-07 07:38 UTC, merged