Module5 task1
htmlacademy-adaptive/1466403-sedona-20 pull request #5
Opened 2020-09-07 20:07 UTC by tgazaryan

2020-09-07 21:02 UTC, ILoyso requested changes

2020-09-07 21:09 UTC, tgazaryan commented on source/less/blocks/features.less
> +
У нас все svg-иконки по умолчанию черные, и по другому не получалось честно говоря изменить цвет. Я изначально и делала через background-image. Та же ситуация с кнопкой с лайком выше :(

2020-09-07 21:12 UTC, tgazaryan commented on source/less/blocks/main-nav.less
> +}
Я не очень поняла 1й комментарий. Имеется ввиду, что сделать просто одно из состояний отдельным классом, и потом просто добавлять модификатор?

2020-09-08 06:30 UTC, ILoyso commented on source/less/blocks/features.less
> +
Можно открыть сам файл svg и изменить/добавить цвет там напрямую

2020-09-08 06:30 UTC, ILoyso commented on source/less/blocks/main-nav.less
> +}
Нет, я имею ввиду, что у нас есть два состояние - закрытое и открытое. Почему бы не сделать, например, открытое дефолтным и написать для него стили без модификатора, а с модификатором "закрытое" только дописать стили, закрывающие меню

2020-09-08 08:53 UTC, tgazaryan commented on source/less/blocks/video.less
> +.video__controls-scale {
То есть проще говоря, две дополнительные обертки не нужны внутри?

2020-09-08 08:57 UTC, ILoyso commented on source/less/blocks/video.less
> +.video__controls-scale {
Да) Лучше фон как-нибудь иначе сделать, а все что внутри рассматривать как контролы одного уровня - кнопки и бар

2020-09-08 09:02 UTC, tgazaryan commented on source/less/blocks/video.less
> +.video__controls-scale {
Значит правильно поняла :)

2020-09-08 09:07 UTC, tgazaryan commented on source/less/blocks/main-nav.less
> +}
А скрипты уже на данном этапе подключать и прикладывать - или это позже?

2020-09-08 09:29 UTC, ILoyso commented on source/less/blocks/main-nav.less
> +}
Можно сейчас, можно потом, без разницы

2020-09-08 11:27 UTC, tgazaryan commented on source/less/blocks/video.less
> +.video__controls-scale {
> Если у .video__container сделать правыми и левыми не паддинги, а марджины (или ограничить ширину и отцентровать), то для video__controls будет достаточно прописать ширину 100% и не нужно будет городить отступы

Это касается планшетной и десктопной версии только?  Или мобильной тоже?
Потому что на мобильной версии изображение в полную ширину экрана, и с марджинами у контейнера, фото ужимается тоже. Или я неправильно понимаю?

2020-09-08 13:46 UTC, ILoyso commented on source/less/blocks/video.less
> +.video__controls-scale {
Это касается десктопа, да. Если ширина 100%, то отступы конечно же не нужны

2020-09-08 14:32 UTC, ILoyso requested changes

2020-09-08 14:32 UTC, ILoyso commented on source/less/blocks/main-nav.less
> +.main-nav .main-nav__toggle {
Здесь модификатора больше нет, поэтому каскад не нужен

2020-09-08 14:32 UTC, ILoyso commented on source/less/blocks/main-nav.less
> +.main-nav .main-nav__list::after {
Аналогично

2020-09-08 14:32 UTC, ILoyso commented on source/less/blocks/main-nav.less
> +.main-nav--closed .main-nav__toggle::before {
Можно написать один раз .main-nav--closed, а все остальное внутри фигурных скобок писать, будет немного покороче (аналогично ниже, соответственно, все что относится к --closed)

2020-09-08 14:32 UTC, ILoyso commented on source/less/blocks/video.less
> +  &--replay {
http://joxi.ru/vAWzXNjTq96NW2
очень большая кнопка получается, отступ слева лучше делать не паддингом кнопки, а паддингом обертки. Аналогично с последней кнопкой

2020-09-08 14:32 UTC, ILoyso commented on source/photo.html
> +              <div class="video__controls-pointer"></div>
Это интерактивный элемент, так что тоже кнопкой лучше делать

2020-09-08 14:32 UTC, ILoyso commented on source/less/blocks/photo.less
> +.photo__like {
http://joxi.ru/LmG9advUJ7n0KA
Давай в блоке с фотографиями тоже по макету сетку разметим, сейчас смещаются блоки влево

2020-09-08 15:41 UTC, tgazaryan commented on source/less/blocks/main-nav.less
> +.main-nav--closed .main-nav__toggle::before {
Я правильно понимаю, что оно будет примерно так?
![9](https://user-images.githubusercontent.com/65111218/92497912-a1679d00-f202-11ea-805f-969a013f2501.PNG)
Ну и далее аналогично с остальными "вложениями"? Или я неправильно понимаю?

2020-09-08 16:14 UTC, ILoyso commented on source/less/blocks/main-nav.less
> +.main-nav--closed .main-nav__toggle::before {
Все правильно :)

2020-09-08 16:49 UTC, ILoyso approved these changes

2020-09-08 16:50 UTC, merged